=== ChrisAtMarmot/ui-rs/src/settings/pullslip-notifications/pullslip-notification.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "description": "A notification schedule for pull-slips associated with locations",
  "additionalProperties": false,
  "properties": {
    "id": {
      "type": "string",
      "maxLength": 36,
      "description": "The UUID of this schedule"
    },
    "name": {
      "type": "string",
      "maxLength": 80,
      "description": "Human-readable name for this schedule"
    },
    "status": {
      "type": "boolean",
      "description": "Whether the notification is active"
    },
    "time": {
      "type": "string",
      "pattern": "^[0-9][0-9]:[0-9][0-9](:[0-9][0-9])?$",
      "description": "The time at which notifications are sent, in 24h format"
    },
    "days": {
      "type": "array",
      "description": "Set of days on which the notification is sent",
      "items": {
        "type": "string",
        "pattern": "^(M|Tu|W|Th|F|Sa|Su)$",
        "description": "Must be one of: M,Tu,W,Th,F,Sa,Su"
      }
    },
    "locations": {
      "type": "array",
      "description": "The locations in which pending pull-slips are sought",
      "items": {
        "type": "string",
        "maxLength": 36,
        "description": "The UUID of a pickup location in the directory"
      }
    },
    "emailAddresses": {
      "type": "array",
      "description": "The addresses to which notifications emails are sent",
      "items": {
        "type": "string",
        "format": "email",
        "pattern": "^[a-z0-9]+@[a-z0-9]+\\.[a-z0-9.]+$",
        "description": "Must be a valid email address"
      }
    }
  },
  "required": [
    "id",
    "time",
    "days",
    "emailAddresses"
  ]
}

=== ChrisAtMarmot/ui-rs/src/settings/pullslip-notifications/example.json
{
  "id": "8f912f63-50ed-42fb-b482-2d64db5fdb91",
  "name": "Weekday report",
  "status": true,
  "time": "15:00:00",
  "days": [
    "M",
    "Tu",
    "W",
    "Th",
    "F"
  ],
  "locations": [
    "747c14ba-fcc4-4aae-aed6-627dd8e0c9d9",
    "71eede4c-c118-4407-ab1e-beee3ed19c6c"
  ],
  "emailAddresses": [
    "mike@indexdata.com",
    "sauropoda@gmail.com"
  ]
}
